application: jalousie-remote
version: 22
runtime: php55
api_version: 1

handlers:
- url: /styles
  static_dir: dist/styles

- url: /fonts
  static_dir: dist/fonts

- url: /scripts
  static_dir: dist/scripts

- url: /views
  static_dir: dist/views

- url: /locales
  static_dir: dist/locales

- url: /login
  script: backend/loginCheck.php

- url: /cmd
  script: backend/cmd.php

- url: /robot
  script: dist/robot.html

- url: .*
  script: dist/index.html

skip_files:
- ^(test/.*)
- ^(node_modules/.*)
- ^(bower_componets/.*)
- ^(app/.*)
- ^(.tmp/.*)
- ^(.sass-cache/.*)
